### ISSUE TITLE
Allow build to set custom namespace  

### ISSUE THREAD

**Issue by bernardkwok** [autodesk-forks/MaterialX#1235]
To avoid possible clashes, it has been recommended to allow for custom namespace setting.
Currently MaterialX has a hard-coded name space but this could be settable via a Cmake option
as is done for OCIO. Then each integration can set it's own namespace to help avoid clashes if MaterialX
is pulled in via multiple integrations.

**Comment by kwokcb** [comment]
This is a duplicate of https://github.com/materialx/MaterialX/issues/773, and is only kept here for local release tracking and assignment.
