### ISSUE TITLE
Support explicit default outputs

### ISSUE THREAD

**Issue by bernardkwok** [autodesk-forks/MaterialX#385]
> [Open in MURAL](https://app.mural.co/t/autodeskdcp2361/m/autodeskdcp2361/1553517942305?wid=0-1556306158228) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> MaterialX Priority Items - Autodesk DCP
  
Under discussion.

**Comment by feldstj** [comment]
Tasks include:
1. Getting rid of isMultiOutputType() as it is no longer needed
2. Add an upgrade path for MaterialX documents to 1.37, this means that nodes and nodedefs should no longer have types but instead one or more output child nodes. We also need to upgrade all of our library and test files with the upgrade path.
3. getNodeDef() needs to take into account not only inputs when determining nodedef matches, but also outputs.
