### ISSUE TITLE
Add in the ability to save edited documents in MaterialX Viewer

### ISSUE THREAD

**Issue by bernardkwok** [autodesk-forks/MaterialX#572]
1.  Currently edits only occur on the generated Shader inputs. This is for speed of feedback and also to avoid expose inputs which actually don't perform any action which can be misleading to the user.

2. In order to save we will require to update the actual document. There are some options here to explore:
   2a. We update on every edit. This could slow things down (to determine)
   2b. We only update at save time. This requires scanning all all Shader inputs and updating corresponding Elements.

_Note 1_: that we must keep the updates of Shader inputs as it is allowable to save and reload the shader source to/from disk. 

_Note 2_:  During save, `<xincludes>` which are explicitly part of the read in document should be written out while those implicitly loaded in via startup library load should not.

_Note 3_: What uniforms are actually available on a Shader for edit is a different topic and has more to do with shader optimization options. There is already a full vs reduced mode, where reduced produces less modifiable inputs. Even in full mode, constants are currently always optimized out even if they are constant nodes. 

There may be additional logic to resolve to find the most suitable approach.

**Comment by fleith** [comment]
The first changes are in #571, but I need to manage the xincludes and do some update on save time (option 2b).
