### ISSUE TITLE
Fix warnings when build the JavaScript bindings

### ISSUE THREAD

**Issue by nikolaf-adsk** [autodesk-forks/MaterialX#907]
There are a couple of warnings that need to be fixed when building the JavaScript bindings.
To reproduce the warnings run: 
```
cmake .. -DMATERIALX_BUILD_JS=ON -DMATERIALX_BUILD_RENDER=OFF -DMATERIALX_BUILD_TESTS=OFF -DMATERIALX_BUILD_GEN_GLSL=OFF -DMATERIALX_BUILD_GEN_OSL=OFF -DMATERIALX_BUILD_GEN_OGSXML=OFF -DMATERIALX_BUILD_GEN_OGSFX=OFF -DMATERIALX_BUILD_GEN_ARNOLD=OFF -DMATERIALX_BUILD_CROSS=OFF -DMATERIALX_BUILD_RUNTIME=OFF -DMATERIALX_BUILD_PYTHON=OFF -DMATERIALX_BUILD_DOCS=OFF -DMATERIALX_EMSDK_PATH={path_to_emsdk}
cmake --build .
```

There are 3 warnings coming from MaterialXCore:
![warning1](https://user-images.githubusercontent.com/61031967/84424485-07795f80-abd5-11ea-8b61-58ec7bd575b5.png)
![warning2](https://user-images.githubusercontent.com/61031967/84424495-0b0ce680-abd5-11ea-8ba6-98cc9f6b463b.png)

There are 2 warnings coming from MaterialXFormat:
![formatwarning](https://user-images.githubusercontent.com/61031967/84424535-16601200-abd5-11ea-9d4c-d35813e1c5da.png)

There are also 2 warnings in the JavaScript cpp bindings if you build without using c++17
![c++17Warnings](https://user-images.githubusercontent.com/61031967/84424597-2d9eff80-abd5-11ea-9568-b636b5f67575.png)

**Comment by bernardkwok** [comment]
Closing. The c++-17 issue can be resolved by building with:
-DCMAKE_CXX_FLAGS='-std=c++17'
