### ISSUE TITLE
Address static analysis issues found in Javascript code

### ISSUE THREAD

**Issue by bernardkwok** [autodesk-forks/MaterialX#924]
There are a number of issues found through static analysis via Codacy.
The important issues should be addressed esp what appear to be security issues:

https://app.codacy.com/gh/autodesk-forks/MaterialX/issues?bid=18872641&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJKYXZhc2NyaXB0Il19LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJTZWN1cml0eSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6W119LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltdfV0=

**Comment by bernardkwok** [comment]
@nikolaf-adsk . Codacy was not working when the Javascript PR went through, so an FYI on these items which you would know better than I if they are real issues or not.

**Comment by nikolaf-adsk** [comment]
I have some changes here: https://github.com/autodesk-forks/MaterialX/pull/925. I will wait for the scan to finish to see if the issues are resolved. There will still be one issue in the test code, but that shouldn't be a problem.

**Comment by nikolaf-adsk** [comment]
I am closing this issue. I merged in https://github.com/autodesk-forks/MaterialX/pull/925
